### ISSUE TITLE
Need a help regarding modern api imp

### ISSUE THREAD

**Issue by Android1500** [anonymix007/ExtA2DP#5]
I also try to impeliment modern api by adding modern lib aar but when i enable module and open it 
give me error  

onBinderReceived
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lio/github/libxposed/service/IXposedService$Stub;
                                                                                                    	at io.github.libxposed.service.XposedServiceHelper.onBinderReceived(XposedServiceHelper.java:40)
                                                                                                    	at io.github.libxposed.service.XposedProvider.call(XposedProvider.java:58)
                                                                                                    	at android.content.ContentProvider.call(ContentProvider.java:2511)
                                                                                                    	at android.content.ContentProvider$Transport.call(ContentProvider.java:525)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1280)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1244)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.libxposed.service.IXposedService$Stub" on path: DexPathList[[zip file "/data/app/~~fGVP96dcUeigEJBEjk7VjQ==/com.example.test3-zMHpWzwbuguIai1BIpztRQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~fGVP96dcUeigEJBEjk7VjQ==/com.example.test3-zMHpWzwbuguIai1BIpztRQ==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at io.github.libxposed.service.XposedServiceHelper.onBinderReceived(XposedServiceHelper.java:40) 
                                                                                                    	at io.github.libxposed.service.XposedProvider.call(XposedProvider.java:58) 
                                                                                                    	at android.content.ContentProvider.call(ContentProvider.java:2511) 
                                                                                                    	at android.content.ContentProvider$Transport.call(ContentProvider.java:525) 
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295) 
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1280) 
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1244) 

any suggestion?

**Comment by anonymix007** [comment]
I don't think I can help you with that. Have you tried building the [example](https://github.com/libxposed/example)?

**Comment by Android1500** [comment]
> I don't think I can help you with that. Have you tried building the [example](https://github.com/libxposed/example)?

Yeah i tried its always show binder null

**Comment by anonymix007** [comment]
You need to first enable it in manager, force stop it in app info and only then it will show non-null binder (and even rotating screen break that). This must be LSPosed bug, report it to developers.
